# Generated by Django 4.1.6 on 2023-02-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(default='')),
                ('personality', models.CharField(max_length=200)),
            ],
        ),
    ]
