# Generated by Django 3.2.12 on 2023-02-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230217_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='book',
            field=models.CharField(default='', max_length=200),
        ),
    ]
